name: "Modular CI"

on: 
  pull_request:
    branches:
      - master

jobs:
  validate:
    name: Validate
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install tooling
        run: |
          bundle install
          brew install mint
          mint install apple/swift-format@swift-5.3-branch
      - name: Check code formatting
        run: |
          swift-format -r -m lint Modular ModularTests
      - name: Run tests
        run: |
          bundle exec fastlane scan
