name: "Modular CI"

on: 
  pull_request:
    branches:
      - master

jobs:
  validate:
    name: Validate
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Checkout
        uses: actions/checkout@master
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: swift-format
          path: /usr/local/bin/swift-format
      - name: swift-format build
        run: |
          if ! [ -x "$(command -v swift-format)" ]; then
            git clone -b swift-5.3-branch https://github.com/apple/swift-format.git
            cd swift-format
            swift build --disable-sandbox -c release
            mv .build .. && cd ..
            sudo cp -f .build/release/swift-format /usr/local/bin/swift-format
          fi
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: swift-format
          path: /usr/local/bin/swift-format
      - name: Check code formatting
        run: |
          sudo swift-format -r -m lint Modular ModularTests
      - name: Install tooling
        run: |
          bundle install
      - name: Run tests
        run: |
          bundle exec fastlane scan
